import { useEffect, useMemo, useState } from 'react';
import { api, auth, ws } from './appdeploy-client';
import { Activity, ArrowUpRight, Bot, BrainCircuit, CheckCircle2, CircleDollarSign, GitBranch, Github, History, LockKeyhole, LogIn, Network, RefreshCw, ShieldCheck, Sparkles, UserCheck, Users, WalletCards, Workflow, XCircle, Zap } from 'lucide-react';

type Mission={id:string;title:string;department:string;status:string;owner:string;budget:number;revenue:number;cost:number;progress:number;verification?:string;action?:string};
type Approval={id:string;missionId?:string;action:string;reason:string;risk:'low'|'medium'|'high';cost:number;reversible:boolean;recommended:'approve'|'reject';status:string};
type Audit={id:string;action:string;missionId?:string;status:string;cost:number;createdAt:string};
type Learning={id:string;missionId?:string;outcome:string;score:number;optimization:string;version:string};
type Agent={id:string;name:string;department:string;role:string;status:string;kpi:number};
type Integration={provider:'github'|'orcid'|'zenodo';connected:boolean;displayName?:string;externalId?:string;connectedAt?:string;configured:boolean};
type Dashboard={missions:Mission[];approvals:Approval[];audit:Audit[];learning:Learning[];agents:Agent[]};
const actions=[['Start Research','research'],['Start Workflow','workflow'],['Execute Mission','execute'],['Approve','approve'],['Reject','reject'],['Pause','pause'],['Resume','resume'],['Expand Team','expand'],['Learn & Optimize','learn'],['Retire Agent','retire'],['Emergency Stop','stop']] as const;
const departments=[{name:'Revenue & Sales',lead:'Revenue Lead',workers:['Market Researcher','Prospector','Outreach Agent','CRM Agent','Proposal Agent']},{name:'Product & Engineering',lead:'Product Lead',workers:['Product Analyst','Builder','QA Agent','Security Agent','Release Agent']},{name:'Regulatory & Knowledge',lead:'Research Lead',workers:['Evidence Researcher','RAG Curator','Compliance Analyst','Citation Agent','Monitor Agent']},{name:'Operations & Finance',lead:'Ops Lead',workers:['Finance Agent','Procurement Agent','Support Agent','Cost Auditor','Payout Agent']}];
const providerLabels={github:'GitHub',orcid:'ORCID',zenodo:'Zenodo'} as const;
function money(v:number){return new Intl.NumberFormat('en-US',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(v);}
function App(){
 const [user,setUser]=useState<any>(null);const [data,setData]=useState<Dashboard>({missions:[],approvals:[],audit:[],learning:[],agents:[]});const [integrations,setIntegrations]=useState<Integration[]>([]);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [active,setActive]=useState('dashboard');const [approval,setApproval]=useState<Approval|null>(null);
 const load=async()=>{setBusy(true);try{const [d,i]=await Promise.all([api.get('/api/control-plane'),auth.isSignedIn()?api.get('/api/integrations'):Promise.resolve({data:{integrations:[]}})]);setData(d.data as Dashboard);setIntegrations(i.data.integrations||[]);}catch(e){setMessage(e instanceof Error?e.message:'Unable to load operating state');}finally{setBusy(false);}};
 const loadUser=async()=>{try{setUser(await auth.getUser());}catch{setUser(null);}};
 useEffect(()=>{void loadUser();void load();const params=new URLSearchParams(window.location.search);const connected=params.get('connected');const error=params.get('oauth_error');if(connected)setMessage((providerLabels as Record<string,string>)[connected]+' connected to your CEO identity.');if(error)setMessage('Connection failed: '+error);if(connected||error)window.history.replaceState({},'',window.location.pathname);const conn=ws.connect();conn.onMessage((m:{type?:string})=>{if(m?.type==='entity.update')void load();});return()=>conn.disconnect();},[]);
 const signIn=async()=>{setBusy(true);try{await auth.signIn({scope:'openid email profile offline_access'});await loadUser();await load();setMessage('Google identity connected. You can now link GitHub, ORCID and Zenodo.');}catch(e){const code=(e as {code?:string}).code;setMessage(code==='popup_blocked'?'Allow the sign-in popup and try again.':code==='popup_closed'?'Sign-in cancelled.':'Google sign-in failed.');}finally{setBusy(false);}};
 const signOut=async()=>{await auth.signOut();setUser(null);setIntegrations([]);setMessage('Signed out.');};
 const act=async(action:string)=>{setBusy(true);try{const r=await api.post('/api/actions',{action}) as {data:{approval?:Approval;message?:string}};if(r.data?.approval)setApproval(r.data.approval);setMessage(r.data?.message||'Action accepted');await load();}catch(e){setMessage(e instanceof Error?e.message:'Action failed');}finally{setBusy(false);}};
 const decide=async(id:string,decision:'approve'|'reject')=>{setBusy(true);try{const r=await api.post('/api/approvals/decision',{approvalId:id,decision});setApproval(null);setMessage(r.data?.message||('Decision '+decision+' recorded'));await load();}catch(e){setMessage(e instanceof Error?e.message:'Decision failed');}finally{setBusy(false);}};
 const connect=async(provider:Integration['provider'])=>{setBusy(true);try{const r=await api.post('/api/integrations/'+provider+'/start',{});window.location.href=(r.data as {authorizationUrl:string}).authorizationUrl;}catch(e){setMessage(e instanceof Error?e.message:'Unable to start '+providerLabels[provider]+' connection');setBusy(false);}};
 const disconnect=async(provider:Integration['provider'])=>{setBusy(true);try{await api.delete('/api/integrations/'+provider);setMessage(providerLabels[provider]+' disconnected.');await load();}catch(e){setMessage(e instanceof Error?e.message:'Unable to disconnect '+provider);}finally{setBusy(false);}};
 const totals=useMemo(()=>data.missions.reduce((a:Mission,m:Mission)=>({revenue:a.revenue+m.revenue,cost:a.cost+m.cost,budget:a.budget+m.budget}),{revenue:0,cost:0,budget:0}),[data.missions]);const profit=totals.revenue-totals.cost;const running=data.missions.filter(m=>m.status==='running').length;
 return <div className="shell"><header className="topbar"><div className="brand"><div className="brand-mark"><Sparkles size={20}/></div><div><strong>WE DO CARE GLOBAL</strong><span>ONE-CLICK AGENT FACTORY · CONTROL PLANE</span></div></div><div className="top-actions">{user?<><span className="identity-pill"><UserCheck size={14}/>{user.name||user.email||'CEO'}</span><button className="secondary small" onClick={()=>void signOut()}>Sign out</button></>:<button className="primary small" onClick={()=>void signIn()} disabled={busy}><LogIn size={14}/> Google Login</button>}<button className="icon-btn" onClick={()=>void load()} title="Refresh"><RefreshCw size={17}/></button></div></header>
 <main className="content">{!user&&<section className="login-banner"><div><p className="eyebrow">CEO IDENTITY</p><h2>Sign in once. Connect the whole research and release stack.</h2><p>Google is the primary AppDeploy identity. After sign-in, GitHub, ORCID and Zenodo are linked to that same CEO account rather than creating separate app identities.</p></div><button className="primary" onClick={()=>void signIn()} disabled={busy}><LogIn size={16}/> Sign in with Google</button></section>}
 <section className="hero"><div><p className="eyebrow">HUMAN → AI LEAD → TEAM LEADS → WORKERS → VERIFIER</p><h1>One click. Full execution. Governed outcomes.</h1><p className="hero-copy">The CEO chooses an action, not a prompt. The control plane infers the plan, binds budget, dispatches work, verifies evidence, records cost and escalates risk.</p><div className="action-grid">{actions.map(([label,key])=><button key={key} className={key==='stop'?'action danger':key==='approve'?'action approval':key==='reject'?'action reject':'action'} onClick={()=>void act(key)} disabled={busy||!user}><Zap size={14}/> {label}</button>)}</div></div><div className="hero-orbit"><div className="orbit-ring ring-a"/><div className="orbit-ring ring-b"/><div className="core"><BrainCircuit size={30}/><span>AI LEAD</span><small>PLAN · DISPATCH · VERIFY</small></div></div></section>
 <section className="metric-grid"><Metric icon={<CircleDollarSign/>} label="Verified revenue" value={money(totals.revenue)} note="verified outcomes"/><Metric icon={<WalletCards/>} label="Tracked cost" value={money(totals.cost)} note="bounded spend"/><Metric icon={<Activity/>} label="Operating profit" value={money(profit)} note="revenue − cost"/><Metric icon={<Workflow/>} label="Bound budgets" value={money(totals.budget)} note="approval protected"/></section>
 <section className="panel"><div className="section-head"><div><p className="eyebrow">IDENTITY FABRIC</p><h2>One CEO identity · four connected systems</h2></div><ShieldCheck size={20}/></div><div className="identity-flow"><div className="identity-core"><LogIn size={17}/><b>{user?'Google / AppDeploy identity':'Google login required'}</b><small>{user?(user.email||user.name||'Authenticated CEO'):'Primary account anchor'}</small></div><div className="identity-links">{integrations.map(i=><IntegrationCard key={i.provider} item={i} onConnect={()=>void connect(i.provider)} onDisconnect={()=>void disconnect(i.provider)} busy={busy}/>)}</div></div></section>
 <section className="panel"><div className="section-head"><div><p className="eyebrow">STATUS CARD</p><h2>CEO operating state</h2></div><span className="status-chip"><CheckCircle2 size={15}/> {running} running · {data.approvals.length} approvals</span></div><div className="status-card"><b>{data.missions[0]?.title||'Factory ready'}</b><span>Status: {data.missions[0]?.status||'ready'}</span><span>What happened: {data.missions[0]?.action||'Control plane is ready for a one-click mission.'}</span><span>Verified outcome: {data.missions[0]?.verification||'pending'}</span><span>Cost: {money(data.missions[0]?.cost||0)}</span><span>Budget remaining: {money(Math.max(0,(data.missions[0]?.budget||0)-(data.missions[0]?.cost||0)))}</span></div></section>
 <section className="panel"><div className="section-head compact"><div><p className="eyebrow">APPROVAL QUEUE</p><h2>One-click governance</h2></div><ShieldCheck size={20}/></div>{data.approvals.length===0?<p className="empty">No pending approvals.</p>:<div className="approval-list">{data.approvals.map(a=><div className="approval-card" key={a.id}><div><b>{a.action}</b><p>{a.reason}</p></div><div className="approval-meta"><span>Risk {a.risk}</span><span>Cost {money(a.cost)}</span><span>Reversible {a.reversible?'yes':'no'}</span><span>Recommended {a.recommended}</span></div><div className="card-actions"><button className="approve-btn" onClick={()=>void decide(a.id,'approve')}>Approve</button><button className="reject-btn" onClick={()=>void decide(a.id,'reject')}>Reject</button></div></div>)}</div>}</section>
 <div className="tabs">{[['dashboard','Dashboard'],['missions','Missions'],['org','Org Chart'],['timeline','Workflow Timeline'],['learning','Learning'],['audit','Audit Ledger']].map(([k,v])=><button key={k} className={active===k?'tab active':'tab'} onClick={()=>setActive(k)}>{v}</button>)}</div>
 {active==='dashboard'&&<><section className="mission-grid">{data.missions.slice(0,6).map(m=><article className="mission-card" key={m.id}><div className="card-top"><span className="tag">{m.department}</span><span className="state">{m.status}</span></div><h3>{m.title}</h3><div className="owner"><Bot size={15}/>{m.owner}</div><div className="progress"><span style={{width:`${m.progress}%`}}/></div><div className="mission-stats"><span><b>{m.progress}%</b> complete</span><span><b>{money(m.cost)}</b> cost</span><span><b>{m.verification||'pending'}</b> verify</span></div></article>)}</section><div className="two-col"><Org data={data.agents}/><Governance/></div></>}
 {active==='missions'&&<PanelList title="Missions" rows={data.missions.map(m=>`${m.title} · ${m.status} · ${money(m.cost)} / ${money(m.budget)} · ${m.verification||'pending'}`)}/>} {active==='timeline'&&<PanelList title="Workflow Timeline" rows={data.missions.map(m=>`[${m.status}] ${m.title} · ${m.progress}% · ${m.owner}`)}/>} {active==='learning'&&<><PanelList title="Learning & Optimization" rows={data.learning.map(l=>`${l.version} · score ${l.score} · ${l.optimization}`)}/><section className="panel"><button className="primary" onClick={()=>void act('learn')} disabled={busy||!user}><BrainCircuit size={16}/> Learn & Optimize now</button></section></>} {active==='audit'&&<PanelList title="Append-only Audit Ledger" rows={data.audit.map(a=>`${new Date(a.createdAt).toLocaleString()} · ${a.action} · ${a.status} · ${money(a.cost)}`)}/>} {active==='org'&&<Org data={data.agents}/>} 
 <section className="panel integrations"><div className="section-head compact"><div><p className="eyebrow">RESEARCH + RELEASE FABRIC</p><h2>GitHub · Zenodo · ORCID</h2></div><button className="secondary small" onClick={()=>void api.post('/api/sync/run',{}).then((r:{data:{message:string}})=>{setMessage(r.data.message);void load()}).catch(e=>setMessage(e instanceof Error?e.message:'Sync failed'))} disabled={busy||!user}><RefreshCw size={14}/> Sync now</button></div><p className="sync-note">External accounts are linked to the authenticated AppDeploy user. Tokens remain server-side and are not exposed to the browser.</p></section>
 <section className="panel bridge"><div><p className="eyebrow">LOCAL AI BRIDGE</p><h2>Cloud ↔ local delegation loop</h2><p>Hermes or another local runtime receives a bounded mission package and returns a receipt. The verifier controls whether the outcome becomes verified.</p></div><div className="bridge-flow"><span>AI LEAD</span><ArrowUpRight size={15}/><span>BRIDGE</span><ArrowUpRight size={15}/><span>LOCAL WORKERS</span><ArrowUpRight size={15}/><span>VERIFIER</span></div></section>{message&&<div className="toast" onClick={()=>setMessage('')}><CheckCircle2 size={16}/>{message}</div>}
 </main><footer>We Do Care Global · One-Click Agent Factory · Unified Identity · Evidence-first · Budget-bounded · Human-governed</footer>{approval&&<div className="modal-backdrop"><div className="approval-modal"><button className="close" onClick={()=>setApproval(null)}><XCircle/></button><p className="eyebrow">CEO APPROVAL</p><h2>{approval.action}</h2><p>{approval.reason}</p><div className="approval-meta"><span>Risk: {approval.risk}</span><span>Cost: {money(approval.cost)}</span><span>Reversible: {approval.reversible?'yes':'no'}</span><span>Recommended: {approval.recommended}</span></div><div className="card-actions"><button className="approve-btn" onClick={()=>void decide(approval.id,'approve')} disabled={busy}><UserCheck/> Approve</button><button className="reject-btn" onClick={()=>void decide(approval.id,'reject')} disabled={busy}><XCircle/> Reject</button></div></div></div>}</div>;
}
function Metric({icon,label,value,note}:{icon:React.ReactNode;label:string;value:string;note:string}){return <div className="metric"><div className="metric-icon">{icon}</div><span>{label}</span><strong>{value}</strong><small>{note}</small></div>}
function IntegrationCard({item,onConnect,onDisconnect,busy}:{item:Integration;onConnect:()=>void;onDisconnect:()=>void;busy:boolean}){return <div className={'provider-card '+(item.connected?'connected':'')}><div className="provider-icon">{item.provider==='github'?<Github/>:<GitBranch/>}</div><div className="provider-main"><b>{providerLabels[item.provider]}</b><span>{item.connected?'Connected':'Not connected'}</span><small>{item.displayName||(item.configured?'Ready to connect':'Provider credentials required')}</small></div>{item.connected?<button className="secondary tiny" onClick={onDisconnect} disabled={busy}>Disconnect</button>:<button className="primary tiny" onClick={onConnect} disabled={busy||!item.configured}>Connect</button>}</div>}
function PanelList({title,rows}:{title:string;rows:string[]}){return <section className="panel"><div className="section-head compact"><div><p className="eyebrow">OPERATIONS</p><h2>{title}</h2></div><History size={20}/></div>{rows.length?rows.map((r,i)=><div className="list-row" key={i}>{r}</div>):<p className="empty">No records yet.</p>}</section>}
function Org({data}:{data:Agent[]}){return <section className="panel"><div className="section-head compact"><div><p className="eyebrow">ORG GRAPH</p><h2>AI workforce</h2></div><Network size={20}/></div><div className="org"><div className="org-node lead"><BrainCircuit size={17}/><div><b>Human CEO</b><small>approval authority</small></div></div><div className="connector"/><div className="org-node ai"><Bot size={17}/><div><b>AI Lead</b><small>plan · dispatch · verify</small></div></div><div className="team-grid">{departments.map(d=><div className="team" key={d.name}><div className="team-head"><Users size={15}/><b>{d.name}</b></div><span className="team-lead">{d.lead}</span>{d.workers.map(w=><span className="worker" key={w}><span className="worker-dot"/>{w}</span>)}</div>)}</div>{data.length>0&&<div className="list-row">Expanded agents: {data.filter(a=>a.status==='active').length} active · {data.filter(a=>a.status==='sandbox').length} sandbox</div>}</div></section>}
function Governance(){return <section className="panel"><div className="section-head compact"><div><p className="eyebrow">TRUST FABRIC</p><h2>Governance</h2></div><ShieldCheck size={20}/></div><div className="guard-list"><Guard title="Budget authority" text="Mission and worker spend cannot exceed the bound envelope."/><Guard title="Human escalation" text="Payments, outreach, deploys, exports, deletion, budget increases and high-risk actions require approval."/><Guard title="Verifier gate" text="Outcomes become verified only after evidence and acceptance checks pass."/><Guard title="Audit ledger" text="Actions, decisions, costs and outcomes are append-only."/><Guard title="Emergency stop" text="Stops new execution and preserves state for recovery."/></div></section>}
function Guard({title,text}:{title:string;text:string}){return <div className="guard"><LockKeyhole size={16}/><div><b>{title}</b><span>{text}</span></div></div>}
export default App;
